name: my-second-workflow
on: workflow_dispatch
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: actions/test-ubuntu-git
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: configure credentials
      uses: docker/login-action@v3.3.0
      with: 
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
